# Generated by Django 4.1 on 2022-09-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('security_number', models.CharField(max_length=255)),
                ('validate_date', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Cartoes',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('verify_digit', models.CharField(max_length=1)),
                ('money', models.DecimalField(decimal_places=2, max_digits=9)),
                ('class_account', models.CharField(choices=[('B', 'Bronze'), ('S', 'Prata'), ('G', 'Ouro'), ('D', 'Diamante')], default='Bronze', max_length=1)),
                ('account_type', models.CharField(choices=[('CC', 'Conta Corrente'), ('CE', 'Conta Essencial'), ('CP', 'Conta Poupança')], default='Conta Corrente', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField()),
                ('loan_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('number_installment', models.PositiveBigIntegerField(max_length=3)),
                ('number_pay_installment', models.PositiveBigIntegerField(max_length=3)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_status', models.CharField(choices=[('AN', 'Analisando'), ('A', 'Aprovado'), ('R', 'Recusado')], default='Analisando', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Emprestimos',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('road', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.CreateModel(
            name='PlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plan_type', models.CharField(choices=[('M', 'MONTHLY'), ('A', 'Anual')], default='MONTHLY', max_length=1)),
                ('installment_date', models.DateField()),
                ('pay_installment_date', models.DateField()),
                ('health_plan', models.CharField(default='UNIMED', max_length=6)),
            ],
            options={
                'verbose_name_plural': 'PlanosSaude',
            },
        ),
        migrations.CreateModel(
            name='SemBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Sem Benefícios Atribuidos', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'SemBeneficios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='ValeAlimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ValeRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'ValeRefeicoes',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('operation_type', models.CharField(choices=[('D', 'Depositar'), ('W', 'Sacar')], default='Depositar', max_length=1)),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('recive_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conta_dinheiro_recebido', to='fast_bank_api.conta')),
                ('sending_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conta_dinheiro_enviada', to='fast_bank_api.conta')),
            ],
            options={
                'verbose_name_plural': 'Transferencias',
            },
        ),
        migrations.CreateModel(
            name='PGTO_Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateField(null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.emprestimo')),
            ],
            options={
                'verbose_name_plural': 'PGTOS_Emprestimos',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_date', models.DateTimeField()),
                ('validate_date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('AGP', 'Aguardando Pagamento'), ('ANP', 'Analisando Pagamento'), ('PA', 'Pagamento Aprovado'), ('PR', 'Pagamento Recusado')], default='Aguardando Pagamento', max_length=3)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.cartao')),
            ],
            options={
                'verbose_name_plural': 'Faturas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField(max_length=3)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('sex_choice', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='Masculino', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_bank_api.conta')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_bank_api.endereco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_bank_api.usuario')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='cartao',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.cliente'),
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('SB', 'Sem Benefício'), ('PS', 'Plano de Saúde'), ('VR', 'Vale Refeição'), ('VA', 'Vale Alimentação')], default='Sem Benefício', max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.cliente')),
            ],
            options={
                'verbose_name_plural': 'Beneficios',
            },
        ),
    ]
