# Generated by Django 4.1 on 2022-09-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_bank_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='number_installment',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='number_pay_installment',
            field=models.PositiveIntegerField(),
        ),
    ]
