# Generated by Django 4.1 on 2022-09-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fast_bank_api', '0002_alter_cliente_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fast_bank_api.conta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fast_bank_api.usuario'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.cartao'),
        ),
        migrations.AlterField(
            model_name='pgto_emprestimo',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.emprestimo'),
        ),
    ]
