# Generated by Django 4.1 on 2022-09-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_bank_api', '0004_rename_address_cliente_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='account_number',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='agency',
            field=models.CharField(max_length=5),
        ),
    ]
