# Generated by Django 4.1 on 2022-09-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_bank_api', '0005_alter_conta_account_number_alter_conta_agency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valealimentacao',
            options={'verbose_name_plural': 'ValeAlimentacoes'},
        ),
    ]
