# Generated by Django 4.1 on 2022-11-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_bank_api', '0009_alter_planosaude_pay_installment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planosaude',
            name='plan_type',
            field=models.CharField(choices=[('M', 'MONTHLY'), ('A', 'ANNUAL')], default='MONTHLY', max_length=1),
        ),
    ]
