# Generated by Django 4.1 on 2022-11-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fast_bank_api', '0010_alter_planosaude_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='planosaude',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sembeneficio',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valealimentacao',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valerefeicao',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fast_bank_api.cliente'),
            preserve_default=False,
        ),
    ]
