# Generated by Django 4.1 on 2022-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_bank_api', '0011_planosaude_client_sembeneficio_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='emission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='validate_date',
            field=models.DateField(),
        ),
    ]
